### ISSUE TITLE
서비스 이용약관

### ISSUE THREAD

**Issue by DongGeon0908** [depromeet/antoon-docs#1]
- 앙뚜앙 서비스 이용약관을 관리합니다

**Comment by DongGeon0908** [comment]
cc. @depromeet/depromeet-exit-1

**Comment by mnxmnz** [comment]
서비스 이용 약관 문서를 저희 팀 노션 말고 여기 레포에서 관리하는 걸까요 ?.?

https://antoon-fun.notion.site/antoon-de39c2292f8441cbae4f3453d6dbcc20
